# Generated by Django 4.2.24 on 2025-09-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_author_publisher_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
