# Generated by Django 4.2.24 on 2025-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_author_bio_author_date_of_birth_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
