# Generated by Django 4.2.24 on 2025-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fine_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
