# Generated by Django 4.2.24 on 2025-09-28 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_member_expiration_date_member_fine_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
