# Generated by Django 4.2.24 on 2025-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_keyword_language_location_remove_member_fine_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
