# Generated by Django 4.2.24 on 2025-11-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_alter_book_language_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='weight',
        ),
    ]
