# Generated by Django 4.2.24 on 2025-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_remove_book_dimensions_remove_book_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='library_app_barcode_e55702_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
