# Generated by Django 4.2.24 on 2025-11-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_remove_book_library_app_barcode_e55702_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
