# Generated by Django 4.2.24 on 2025-11-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0018_delete_keyword_book_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': [('manage_books', 'Can manage books (CRUD)')]},
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'permissions': [('manage_borrows', 'Can manage borrow/return')]},
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='library_app.book'),
        ),
    ]
