# Generated by Django 4.2.24 on 2025-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0019_alter_book_options_alter_borrowrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image (JPG, PNG, GIF). Max size: 5MB', null=True, upload_to='book_covers/'),
        ),
    ]
