# Generated by Django 4.2.24 on 2025-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0021_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fine_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
