# Generated by Django 4.2.24 on 2025-11-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0022_member_fine_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
