# Generated by Django 4.2.24 on 2025-11-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0023_member_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
    ]
