# Generated by Django 4.2.24 on 2025-11-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0025_member_card_number'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE library_app_member SET card_number = CONCAT('LIB', UPPER(SUBSTRING(MD5(RAND()), 1, 8))) WHERE card_number IS NULL OR card_number = ''",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
