# Generated by Django 4.2.24 on 2025-11-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0026_auto_20251108_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
    ]
