# Generated by Django 4.2.24 on 2025-11-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0028_member_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
